### ISSUE TITLE
Unable to connect to rtorrent. Check if rtorrent is running.

### ISSUE THREAD

**Issue by varoOP** [Magicalex/rtorrent-cleaner#2]
It gives me the report, when I run : 
`rtorrent-cleaner report --scgi=localhost --port=5000`
But when I run `rtorrent-cleaner rm`
It gives me error.

**Comment by al3xLvs** [comment]
it's normal

```
rtorrent-cleaner report --scgi=localhost --port=5000
rtorrent-cleaner rm --scgi=localhost --port=5000
```

**Comment by al3xLvs** [comment]
@varoOP problem solved?
