### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by danoldlib** [Magicalex/rtorrent-cleaner#6]
I saw you had a closed issue for this with a previous version but I've been having the same issue.

rtorrent-cleaner report --exclude-dirs=Music /var/run/dan/.rtorrent.sock 
┌───────────────────────────┐
│ rtorrent-cleaner - report │
└───────────────────────────┘

 ████████████████████████████ 100%
 remaining time: < 1 sec
 status: completed successfully!st from rtorrent...

In RecursiveDirectoryIterator.php line 48:
                                                                                                                                                                              
  RecursiveDirectoryIterator::__construct(/home/dan/torrents/rtorrent/download/Music/SOME FOLDER: failed to open dir: Too many open files  
                                                                                                                                                                              

report [-f|--exclude-files EXCLUDE-FILES] [-d|--exclude-dirs EXCLUDE-DIRS] [-l|--log [LOG]] [--] <scgi>

I ran: find /home/dan/torrents/rtorrent/download/ -type f | wc -l
111974

and

find /home/dan/torrents/rtorrent/download/ -type d | wc -l
5838

I'm running version 0.9.8

Thanks!

**Comment by al3xLvs** [comment]
100k files... Maybe it's a limitation of your operating system. Check this https://stackoverflow.com/a/14749074

**Comment by danoldlib** [comment]
Thanks! Looks like that did the trick.
